movie/urls.py
from django.urls import path, include
from . import views
from .views import MovieArchiveView

app_name = 'try'

urlpatterns = [
   path('', views.index, name='index'),
   path('detail/<str:pk>', views.detail, name='detail'),
   path('genre/<str:genre>', views.genreView, name='genre'),
   path('language/<str:language>', views.languageView, name='language'),
   path('year/<int:year>', MovieArchiveView.as_view(), name='year'),
]

try/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('',include('movie.urls',namespace='movies')),
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/models.py
from django.db import models


GENRE_CHOICES = (

('action','action'),
('comedy','comedy'),
('romantic','romantic'),
('drama','drama'),
('sad','sad'),
('horror','horror'),

)


LANGUAGE_CHOICES = (                                                                                                                                                                          
                                                                                                                                                                                              
    ('english','english'),                                                                                                                                                                         
    ('spanish','spanish'),                                                                                                                                                                          
    ('nepali','nepali'),                                                                                                                                                                          
                                                                                                                                                                                              
)  



# Create your models here.
class Movie(models.Model):

    name = models.CharField(max_length=20)
    description = models.CharField(max_length=250)
    genre = models.CharField(choices=GENRE_CHOICES ,max_length=20)
    casts = models.CharField(max_length=200)
    language = models.CharField(choices=LANGUAGE_CHOICES ,max_length=200)
    director = models.CharField(max_length=200)
    update_time = models.DateField(auto_now_add=True)
    release_date = models.DateField(null=True,blank=True)
    length = models.IntegerField()
    budget = models.IntegerField()
    image = models.ImageField(upload_to='movies')
    
    def __str__(self):
        return self.name

movie/views.py
from django.shortcuts import render
from .models import *
from django.core.paginator import Paginator ,EmptyPage,PageNotAnInteger
from django.db.models import Q
from django.views.generic.list import ListView
from django.http import HttpResponse

from django.views.generic.dates import YearArchiveView

# Create your views here.



def index(request):
    template_name = 'index.html'
    if request.method == 'GET':
        query_list = Movie.objects.filter()
        query = request.GET.get('search')
        if query:
            query_list  = Movie.objects.filter(
              Q(name__icontains=query )| Q(description__icontains=query)
                 )
   

    paginator = Paginator(query_list,3)
    page = request.GET.get('page')

    try:
        queries = paginator.page(page)
    
    except PageNotAnInteger:
        queries = paginator.page(1)
    
    except EmptyPage:
        queries = paginator.page(paginator.num_pages)

    context = {
        
       
        'movies' : queries,
       
        

    }
    return render(request,template_name,context)   



def detail(request,pk):  
    template_name = 'detail.html'
    movies = Movie.objects.get(pk=pk)
    context = {
        'movies' : movies       

    }
    return render(request,template_name,context)    


def genreView(request,genre):
  
    movies = Movie.objects.filter(genre=genre)
    paginator = Paginator(movies,3)
    page = request.GET.get('page')
    try:
        queries = paginator.page(page)
    
    except PageNotAnInteger:
        queries = paginator.page(1)
    
    except EmptyPage:
        queries = paginator.page(paginator.num_pages)
    context = {
        'movie_category' : queries,
        'movies' : queries    

    }
    return render(request, "genre.html", context)



def languageView(request,language):

    template_name = 'language.html'
    movies = Movie.objects.filter(language=language)
    paginator = Paginator(movies,3)
    page = request.GET.get('page')
    try:
        queries = paginator.page(page)
    
    except PageNotAnInteger:
        queries = paginator.page(1)
    
    except EmptyPage:
        queries = paginator.page(paginator.num_pages)
    context = {
        'movie_language' : queries,
        'movies' : queries
        

    }
    return render(request,template_name,context)   

class MovieArchiveView(YearArchiveView):

    paginate_by = 3
 
    queryset = Movie.objects.all()

    print(queryset)
    date_field = "release_date"
    make_object_list = True
    allow_future = True

movie/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
      
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Movie</title>
  </head>
  <body>
   

   <nav class="navbar navbar-dark bg-primary  navbar-expand-lg">
  <a class="navbar-brand" href="{% url 'try:index' %}">Movie</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'try:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
     <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Genre
        </a>    
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
  
          <a class="dropdown-item" href="{% url 'try:genre' 'action' %}">Action</a>
          <a class="dropdown-item" href="{% url 'try:genre' 'comedy' %}">Comedy</a>
          <a class="dropdown-item" href="{% url 'try:genre' 'romantic' %}">Romantic</a>
          <a class="dropdown-item" href="{% url 'try:genre' 'drama' %}">Drama</a>
          <a class="dropdown-item" href="{% url 'try:genre' 'sad' %}">Sad</a>
          <a class="dropdown-item" href="{% url 'try:genre' 'horror' %}">Horror</a>
       
        </div>
      </li> 
          <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Year
        </a>    
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'try:year'   year=2018 %}">2018</a>
          <a class="dropdown-item" href="{% url 'try:year'   year=2019 %}">2019</a>
          <a class="dropdown-item" href="{% url 'try:year'   year=2020 %}">2020</a>
      
       

        </div>
      </li> 
    <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Language
        </a>    
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'try:language' 'english' %}">English</a>
          <a class="dropdown-item" href="{% url 'try:language' 'nepali' %}">Nepali</a>
          <a class="dropdown-item" href="{% url 'try:language' 'spanish' %}">Spanish</a>
      
       
        </div>
      </li> 
    </ul>
    <form class="form-inline my-2 my-lg-0 " method='GET' action='{% url "try:index"  %}'>
      <input class="form-control mr-sm-2" type="search" placeholder="Search" value="{{ request.GET.search  }}" aria-label="Search" name='search' >
      <button class="btn btn-outline-success my-2 my-sm-0 active" type="submit">Search</button>
    </form>
  </div>
</nav>


{% block body %}


{% endblock body %}



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


   </body>
</html>

movie/templates/detail.html
{% extends "base.html" %}
{% load static %}
{% block body %}




<div class=" text-center">
    <div class="card-header text-white bg-info ">
     Movie-Name
  </div>
    
    <div class="text-white bg-secondary"  >
       <img style="width: 200px; height: 200px;" src="{% static 'img/linux.png' %}" class="card-img-top" alt="...">

    </div>
  <div class="card-body text-white bg-secondary " >  
        <h8 class="card-title">Movie Name: {{movies.name}}  </h8><br>
        <h8 class="card-title">Genre    : {{movies.genre}} </h8><br>
        <h8 class="card-title">Release-Date: {{movies.release_date}}  </h8><br>
        <h8 class="card-title">Casts       : {{movies.casts}}  </h8><br>
        <h8 class="card-title">Length       : {{movies.length}}  </h8><br>
        <h8 class="card-title">Language       :  {{movies.language}} </h8><br>
        <h8 class="card-title"> Budget    : {{movies.budget}}  </h8>
  
  
  </div>
  <div class="card-footer text-white bg-info ">
  IMDB-Rating: 10/10
  </div>
</div>

{% endblock body %}

movie/templates/genre.html
{% extends "base.html" %}
{% load static %}
{% block body %}
    <link rel="stylesheet" href="{% static 'css/img.css' %}" >
<br><br><br>        



 <div class="container">
<div class="card-deck">
     {% if movie_category %}
 {% for movie in movie_category  %}
    

        <div class="card text-white bg-info mb-3" >
        <img src="{{movie.image.url}}" class="card-img-top" alt="...">
        <div class="card-body">
            <a class="card-title"  style="color:yellow"  href="{% url 'try:detail' movie.pk %}">{{movie.name | title}} </a>
        <p class="card-text">{{movie.description | title}}</p>
        </div>
        <div class="card-footer" >
        <small  class="text-white"></small>
        </div>
    </div>

     {% endfor %}
 {% endif %}
    </div> 



 

						



 <div class="pagination container">

 {% if movies.has_previous %}


<li class="page-item ">

<a href="?page={{ movies.previous_page_number }}"  class="page-link" >&laquo;previous</a>
 {% endif %}
{% for p in movies.paginator.page_range %}

{% if movies.number == p %}

<li class="page-item active">

<a href="?page={{p}}" class="page-link" >{{p}}</a>

</li>
{% else %}

<li class="page-item ">

<a href="?page={{p}}" class="page-link" >{{p}}</a>

</li>


{% endif %}
{% endfor %}


 {% if movies.has_next%}


<li class="page-item ">

<a href="?page={{ movies.next_page_number }}"  class="page-link" >&raquo;next</a>
 {% endif %}

{% endblock body %}

movie/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block body %}
    <link rel="stylesheet" href="{% static 'css/img.css' %}" >
<br><br><br>        



<div class="container">

  
 <div class="row row-cols-1 row-cols-md-3" style="width:1200px;height:600px;"> {% for movie in movies %}
  <div class="col mb-4" >
    <div class="card">
      <img src="{{movie.image.url}}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{movie.title}}</h5>
        <p class="card-text">{{movie.description}}</p>
      </div>
       <div class="card-footer" >
      <small  class="text-dark">{{movie.update_time}}</small>
    </div>
    </div>
  </div>  {% endfor %}
  </div>
  
  </div>
  

 <div class="pagination container">

 {% if movies.has_previous %}


<li class="page-item ">
<a href="?page=1" class="page-link">&laquo; first</a></li>  
<li class="page-item ">
<a href="?page={{ movies.previous_page_number }}"  class="page-link" >&laquo;previous</a></li>
 {% endif %}
{% for p in movies.paginator.page_range %}

{% if movies.number == p %}

<li class="page-item active">
<a href="?page={{p}}" class="page-link" >{{p}}</a>

</li>
{% else %}

<li class="page-item ">

<a href="?page={{p}}" class="page-link" >{{p}}</a>

</li>


{% endif %}
{% endfor %}


 {% if movies.has_next%}


<li class="page-item ">

<a href="?page={{ movies.next_page_number }}"  class="page-link" >next &raquo;</a></li>
<li class="page-item ">
<a href="?page={{ movies.paginator.num_pages }} " class="page-link">last</a></li>

 {% endif %}

{% endblock body %}

movie/templates/language.html
{% extends "base.html" %}
{% load static %}
{% block body %}
    <link rel="stylesheet" href="{% static 'css/img.css' %}" >
<br><br><br>        



 <div class="container">
<div class="card-deck">
     {% if movie_language %}
 {% for movie in movie_language  %}
    

        <div class="card text-white bg-info mb-3" >
        <img src="{{movie.image.url}}" class="card-img-top" alt="...">
        <div class="card-body">
            <a class="card-title"  style="color:yellow"  href="{% url 'try:detail' movie.pk %}">{{movie.name | title}} </a>
        <p class="card-text">{{movie.description | title}}</p>
        </div>
        <div class="card-footer" >
        <small  class="text-white"></small>
        </div>
    </div>

     {% endfor %}
 {% endif %}
    </div> 



 
  
 <div class="pagination container">

 {% if movies.has_previous %}


<li class="page-item ">

<a href="?page={{ movies.previous_page_number }}"  class="page-link" >&laquo;previous</a>
 {% endif %}
{% for p in movies.paginator.page_range %}

{% if movies.number == p %}

<li class="page-item active">

<a href="?page={{p}}" class="page-link" >{{p}}</a>

</li>
{% else %}

<li class="page-item ">

<a href="?page={{p}}" class="page-link" >{{p}}</a>

</li>


{% endif %}
{% endfor %}


 {% if movies.has_next%}


<li class="page-item ">

<a href="?page={{ movies.next_page_number }}"  class="page-link" >&raquo;next</a>
 {% endif %}

{% endblock body %}

movie/templates/movie/movie_archive_year.html
{% extends "base.html" %}
{% load static %}
{% block body %}
    <link rel="stylesheet" href="{% static 'css/img.css' %}" >
<br><br><br>        


<div class="container">
<div class="card-deck">
  {% for movie in object_list %}
  

    <div class=" card text-white bg-info mb-3" >
    <img src="{{movie.image.url}}" class="card-img-top" alt="...">
    <div class="card-body">
        <a class="card-title"  style="color:yellow"  href="{% url 'try:detail' movie.pk %}">{{movie.name}}</a>
      <p class="card-text">{{movie.description}}</p>
    </div>
    <div class="card-footer" >
      <small  class="text-white">{{movie.update_time}}</small>
    </div>
  </div>

  {% endfor %}
</div>




 <div class="pagination container">

 {% if page_obj.has_previous %}


<li class="page-item ">
<a href="?page=1" class="page-link">&laquo; first</a></li>  
<li class="page-item ">
<a href="?page={{ page_obj.previous_page_number }}"  class="page-link" >&laquo;previous</a></li>
 {% endif %}
{% for p in page_obj.paginator.page_range %}

{% if page_obj.number == p %}

<li class="page-item active">
<a href="?page={{p}}" class="page-link" >{{p}}</a>

</li>
{% else %}

<li class="page-item ">

<a href="?page={{p}}" class="page-link" >{{p}}</a>

</li>


{% endif %}
{% endfor %}


 {% if page_obj.has_next%}


<li class="page-item ">

<a href="?page={{ page_obj.next_page_number }}"  class="page-link" >next &raquo;</a></li>
<li class="page-item ">
<a href="?page={{ page_obj.paginator.num_pages }} " class="page-link">last</a></li>

 {% endif %}



{% endblock body %}